language: node_js

node_js:
  - stable

cache:
  directories:
    - node_modules

branches:
  only:
    - source

install: npm install

before_script:
  - git config --global user.name "Leonid Zolotarev"
  - git config --global user.email "leoz@yahoo.com"
  - sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script:
  - hexo generate

deploy:
  skip_cleanup: true
  provider: script
  script: sh deploy.sh
  on:
    branch: source
